sudo: false
dist: trusty
language: ruby
rvm: 2.6.5
cache: bundler
bundler_args: --retry=6
before_install:
  - gem install bundler:2.1.4 --no-rdoc --no-ri
branches:
  only:
    - master
    - /^int-.*$/
    - /^release-.*$/
script:
  - bundle exec rake spec
